const style = {
  middleSection: {
    backgroundColor: "rgba(216, 216, 216, 0.15)",
    margin: 0,
    padding: "75px 0",
    position: "relative",
  },
  cocktailBarContainer: {
    backgroundColor: "white",
    maxWidth: "400px",
    position: "absolute",
    zIndex: 1,
    top: "50%",
    right: "15%",
    transform: "translate(0,-50%)",
    display: "block",
    paddingRight: "50px",
    paddingLeft: "50px",
    paddingTop: "50px",
    paddingBottom: "50px",
  },
  preTitle: {
    fontSize: "14px",
    color: "#D8272E",
    letterSpacing: "2px",
    fontWeight: 600,
    marginTop: 0,
    marginBottom: "10px",
  },
  title: {
    fontSize: "56px",
    color: "black",
    letterSpacing: "2px",
    lineHeight: "60px",
    fontStyle: "italic",
    marginBottom: "0.5rem",
    fontWeight: 300,
  },
  textsContainer: {
    height: "272px",
    overflow: "scroll",
    marginTop: "35px",
  },
  cocktailText: {
    fontSize: "16px",
    letterSpacing: 0,
    lineHeight: "28px",
    color: "black",
    marginTop: 0,
    marginBottom: "1rem",
  },
  textsButton: {
    color: "#D8272E",
    fontSize: "16px",
    letterSpacing: 0,
    lineHeight: "28px",
    backgroundColor: "transparent",
    border: "none",
  },
  bookingButton: {
    padding: "12px 20px",
    color: "#D8272E",
    backgroundColor: "transparent",
    marginTop: "50px",
    fontSize: "14px",
    fontWeight: 500,
    letterSpacing: "2.67px",
    borderTop: "1px solid #D8272E",
    borderBottom: "1px solid #D8272E",
    borderLeft: "1px solid #D8272E",
    borderRight: "none",
  },
  imgContainer: {
    paddingRight: "15px",
    paddingLeft: "15px",
    boxSizing: "border-box",
  },
  diningImage: {
    height: "760px",
    display: "block",
    objectFit: "cover",
  },
};
export default style;
